### ISSUE TITLE
Blending is broken in html5

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#286]
http://i.imgur.com/XpnUVbS.png
this image is from dmitryhryppa, the same is happening in my game.
The problem don't happen in Linux (the only other target that I'm testing).

**Comment by laxa88** [comment]
I can vouch for this issue; don't know when it got broken, but luckily I recorded the last working commit for kha that I used for my game (bfeaea597e90).

**Comment by RobDangerous** [comment]
Is it fixed now? If not I could need a small sample

**Comment by RafaelOliveira** [comment]
Its not fixed. Here is a example
https://www.dropbox.com/s/qmk9ythdw88uzxa/TestBug.zip?dl=0
The background is ok, but the trees rendered on top are with the "ghost effect".

**Comment by laxa88** [comment]
Issue isn't fixed yet. tested today. It's as Rafael says.

**Comment by RobDangerous** [comment]
Rafael's sample works for me since 64db1a1, is your Kha really fully up to date?

**Comment by laxa88** [comment]
I just did a git pull, the latest commit I have on log is f6ac0e32ca9f. Is this correct?

**Comment by RobDangerous** [comment]
Yes, that's fine. Did you check Rafael's sample?

**Comment by laxa88** [comment]
Oh okay. Rafael's sample works, but not mine. I'll troubleshoot my project first and get back to you.

**Comment by laxa88** [comment]
package;

    import kha.Assets;
    import kha.Framebuffer;
    import kha.Scheduler;
    import kha.System;
    import kha.Image;
    import kha.Scaler;

    class Project 
    {
        var backbuffer:Image;

    	public function new() 
        {
            Assets.loadEverything(assetsLoaded);		
    	}
        
        function assetsLoaded():Void
        {
            System.notifyOnRender(render);
    		Scheduler.addTimeTask(update, 0, 1 / 60);

            backbuffer = Image.createRenderTarget(800, 600);
        }

    	function update():Void 
        {
    		
    	}

    	function render(framebuffer:Framebuffer):Void 
        {
            backbuffer.g2.begin(true);
            backbuffer.g2.drawImage(Assets.images.bg, 0, 0);
            backbuffer.g2.drawImage(Assets.images.tree, 50, 50);
            // backbuffer.g2.pushOpacity(0.5);
            backbuffer.g2.drawImage(Assets.images.tree, 250, 50);
            // backbuffer.g2.popOpacity();
            backbuffer.g2.end();

            framebuffer.g2.begin(true, 0xFFFFFFF);
            Scaler.scale(backbuffer, framebuffer, System.screenRotation);
            framebuffer.g2.end();
    	}
    }

Here's a modification of Rafael's test project. If you uncomment the pushOpacity and popOpacity lines, you'll get the bug I mentioned. The problem is caused by

    framebuffer.g2.begin(true, 0xFFFFFFFF);

If you omit the 0xFFFFFFFF, the image renders fine.
